# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getrangedlg.ui'
#
# Created: Wed Jun  4 10:46:29 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_getrangedlg(object):
    def setupUi(self, getrangedlg):
        getrangedlg.setObjectName("getrangedlg")
        getrangedlg.resize(930, 619)
        self.buttonBox = QtGui.QDialogButtonBox(getrangedlg)
        self.buttonBox.setGeometry(QtCore.QRect(740, 550, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(getrangedlg)
        self.label.setGeometry(QtCore.QRect(70, 80, 101, 17))
        self.label.setObjectName("label")
        self.xrangemin = QtGui.QDoubleSpinBox(getrangedlg)
        self.xrangemin.setGeometry(QtCore.QRect(280, 260, 91, 27))
        self.xrangemin.setDecimals(3)
        self.xrangemin.setMinimum(6500.0)
        self.xrangemin.setMaximum(6650.0)
        self.xrangemin.setSingleStep(0.001)
        self.xrangemin.setObjectName("xrangemin")
        self.label_3 = QtGui.QLabel(getrangedlg)
        self.label_3.setGeometry(QtCore.QRect(500, 270, 41, 17))
        self.label_3.setObjectName("label_3")
        self.xrangemax = QtGui.QDoubleSpinBox(getrangedlg)
        self.xrangemax.setGeometry(QtCore.QRect(550, 260, 91, 27))
        self.xrangemax.setDecimals(3)
        self.xrangemax.setMinimum(6500.0)
        self.xrangemax.setMaximum(6650.0)
        self.xrangemax.setSingleStep(0.01)
        self.xrangemax.setProperty("value", 6650.0)
        self.xrangemax.setObjectName("xrangemax")
        self.rlmp1 = QtGui.QPushButton(getrangedlg)
        self.rlmp1.setGeometry(QtCore.QRect(410, 280, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlmp1.setFont(font)
        self.rlmp1.setAutoRepeat(True)
        self.rlmp1.setObjectName("rlmp1")
        self.rlmp5 = QtGui.QPushButton(getrangedlg)
        self.rlmp5.setGeometry(QtCore.QRect(440, 280, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlmp5.setFont(font)
        self.rlmp5.setAutoRepeat(True)
        self.rlmp5.setObjectName("rlmp5")
        self.rlpp1 = QtGui.QPushButton(getrangedlg)
        self.rlpp1.setGeometry(QtCore.QRect(410, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlpp1.setFont(font)
        self.rlpp1.setAutoRepeat(True)
        self.rlpp1.setObjectName("rlpp1")
        self.rlpp5 = QtGui.QPushButton(getrangedlg)
        self.rlpp5.setGeometry(QtCore.QRect(440, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlpp5.setFont(font)
        self.rlpp5.setAutoRepeat(True)
        self.rlpp5.setObjectName("rlpp5")
        self.rump1 = QtGui.QPushButton(getrangedlg)
        self.rump1.setGeometry(QtCore.QRect(670, 280, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rump1.setFont(font)
        self.rump1.setAutoRepeat(True)
        self.rump1.setObjectName("rump1")
        self.rupp1 = QtGui.QPushButton(getrangedlg)
        self.rupp1.setGeometry(QtCore.QRect(670, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rupp1.setFont(font)
        self.rupp1.setAutoRepeat(True)
        self.rupp1.setObjectName("rupp1")
        self.rump5 = QtGui.QPushButton(getrangedlg)
        self.rump5.setGeometry(QtCore.QRect(700, 280, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rump5.setFont(font)
        self.rump5.setAutoRepeat(True)
        self.rump5.setObjectName("rump5")
        self.rupp5 = QtGui.QPushButton(getrangedlg)
        self.rupp5.setGeometry(QtCore.QRect(700, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rupp5.setFont(font)
        self.rupp5.setAutoRepeat(True)
        self.rupp5.setObjectName("rupp5")
        self.srlmp5 = QtGui.QPushButton(getrangedlg)
        self.srlmp5.setGeometry(QtCore.QRect(430, 480, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlmp5.setFont(font)
        self.srlmp5.setAutoRepeat(True)
        self.srlmp5.setObjectName("srlmp5")
        self.srlpp1 = QtGui.QPushButton(getrangedlg)
        self.srlpp1.setGeometry(QtCore.QRect(400, 460, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlpp1.setFont(font)
        self.srlpp1.setAutoRepeat(True)
        self.srlpp1.setObjectName("srlpp1")
        self.srlpp5 = QtGui.QPushButton(getrangedlg)
        self.srlpp5.setGeometry(QtCore.QRect(430, 460, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlpp5.setFont(font)
        self.srlpp5.setAutoRepeat(True)
        self.srlpp5.setObjectName("srlpp5")
        self.srupp1 = QtGui.QPushButton(getrangedlg)
        self.srupp1.setGeometry(QtCore.QRect(660, 460, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srupp1.setFont(font)
        self.srupp1.setAutoRepeat(True)
        self.srupp1.setObjectName("srupp1")
        self.label_9 = QtGui.QLabel(getrangedlg)
        self.label_9.setGeometry(QtCore.QRect(490, 470, 16, 17))
        self.label_9.setObjectName("label_9")
        self.srupp5 = QtGui.QPushButton(getrangedlg)
        self.srupp5.setGeometry(QtCore.QRect(690, 460, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srupp5.setFont(font)
        self.srupp5.setAutoRepeat(True)
        self.srupp5.setObjectName("srupp5")
        self.srlmp1 = QtGui.QPushButton(getrangedlg)
        self.srlmp1.setGeometry(QtCore.QRect(400, 480, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlmp1.setFont(font)
        self.srlmp1.setAutoRepeat(True)
        self.srlmp1.setObjectName("srlmp1")
        self.srump5 = QtGui.QPushButton(getrangedlg)
        self.srump5.setGeometry(QtCore.QRect(690, 481, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srump5.setFont(font)
        self.srump5.setAutoRepeat(True)
        self.srump5.setObjectName("srump5")
        self.srump1 = QtGui.QPushButton(getrangedlg)
        self.srump1.setGeometry(QtCore.QRect(660, 480, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srump1.setFont(font)
        self.srump1.setAutoRepeat(True)
        self.srump1.setObjectName("srump1")
        self.srmin = QtGui.QDoubleSpinBox(getrangedlg)
        self.srmin.setGeometry(QtCore.QRect(270, 470, 91, 27))
        self.srmin.setDecimals(3)
        self.srmin.setMinimum(6500.0)
        self.srmin.setMaximum(6650.0)
        self.srmin.setSingleStep(0.001)
        self.srmin.setProperty("value", 6530.0)
        self.srmin.setObjectName("srmin")
        self.srmax = QtGui.QDoubleSpinBox(getrangedlg)
        self.srmax.setGeometry(QtCore.QRect(540, 470, 91, 27))
        self.srmax.setDecimals(3)
        self.srmax.setMinimum(6500.0)
        self.srmax.setMaximum(6650.0)
        self.srmax.setSingleStep(0.001)
        self.srmax.setProperty("value", 6600.0)
        self.srmax.setObjectName("srmax")
        self.srbmp1 = QtGui.QPushButton(getrangedlg)
        self.srbmp1.setGeometry(QtCore.QRect(770, 480, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbmp1.setFont(font)
        self.srbmp1.setAutoRepeat(True)
        self.srbmp1.setObjectName("srbmp1")
        self.rbmp5 = QtGui.QPushButton(getrangedlg)
        self.rbmp5.setGeometry(QtCore.QRect(810, 280, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbmp5.setFont(font)
        self.rbmp5.setAutoRepeat(True)
        self.rbmp5.setObjectName("rbmp5")
        self.rbpp1 = QtGui.QPushButton(getrangedlg)
        self.rbpp1.setGeometry(QtCore.QRect(780, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbpp1.setFont(font)
        self.rbpp1.setAutoRepeat(True)
        self.rbpp1.setObjectName("rbpp1")
        self.srbpp1 = QtGui.QPushButton(getrangedlg)
        self.srbpp1.setGeometry(QtCore.QRect(770, 460, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbpp1.setFont(font)
        self.srbpp1.setAutoRepeat(True)
        self.srbpp1.setObjectName("srbpp1")
        self.rbpp5 = QtGui.QPushButton(getrangedlg)
        self.rbpp5.setGeometry(QtCore.QRect(810, 260, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbpp5.setFont(font)
        self.rbpp5.setAutoRepeat(True)
        self.rbpp5.setObjectName("rbpp5")
        self.srbpp5 = QtGui.QPushButton(getrangedlg)
        self.srbpp5.setGeometry(QtCore.QRect(800, 460, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbpp5.setFont(font)
        self.srbpp5.setAutoRepeat(True)
        self.srbpp5.setObjectName("srbpp5")
        self.rbmp1 = QtGui.QPushButton(getrangedlg)
        self.rbmp1.setGeometry(QtCore.QRect(780, 280, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbmp1.setFont(font)
        self.rbmp1.setAutoRepeat(True)
        self.rbmp1.setObjectName("rbmp1")
        self.srbmp5 = QtGui.QPushButton(getrangedlg)
        self.srbmp5.setGeometry(QtCore.QRect(800, 480, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbmp5.setFont(font)
        self.srbmp5.setAutoRepeat(True)
        self.srbmp5.setObjectName("srbmp5")
        self.label_10 = QtGui.QLabel(getrangedlg)
        self.label_10.setGeometry(QtCore.QRect(790, 220, 41, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.datafiles = QtGui.QListWidget(getrangedlg)
        self.datafiles.setGeometry(QtCore.QRect(220, 20, 431, 192))
        self.datafiles.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.datafiles.setObjectName("datafiles")
        self.selcolour = QtGui.QPushButton(getrangedlg)
        self.selcolour.setGeometry(QtCore.QRect(60, 390, 121, 27))
        self.selcolour.setObjectName("selcolour")
        self.colourdisp = QtGui.QGraphicsView(getrangedlg)
        self.colourdisp.setGeometry(QtCore.QRect(230, 370, 151, 61))
        self.colourdisp.setObjectName("colourdisp")
        self.selectx = QtGui.QCheckBox(getrangedlg)
        self.selectx.setGeometry(QtCore.QRect(60, 260, 131, 22))
        self.selectx.setObjectName("selectx")
        self.rlp1 = QtGui.QPushButton(getrangedlg)
        self.rlp1.setGeometry(QtCore.QRect(410, 240, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlp1.setFont(font)
        self.rlp1.setAutoRepeat(True)
        self.rlp1.setObjectName("rlp1")
        self.rlp5 = QtGui.QPushButton(getrangedlg)
        self.rlp5.setGeometry(QtCore.QRect(440, 240, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlp5.setFont(font)
        self.rlp5.setAutoRepeat(True)
        self.rlp5.setObjectName("rlp5")
        self.rup1 = QtGui.QPushButton(getrangedlg)
        self.rup1.setGeometry(QtCore.QRect(670, 240, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rup1.setFont(font)
        self.rup1.setAutoRepeat(True)
        self.rup1.setObjectName("rup1")
        self.rup5 = QtGui.QPushButton(getrangedlg)
        self.rup5.setGeometry(QtCore.QRect(700, 240, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rup5.setFont(font)
        self.rup5.setAutoRepeat(True)
        self.rup5.setObjectName("rup5")
        self.rbp1 = QtGui.QPushButton(getrangedlg)
        self.rbp1.setGeometry(QtCore.QRect(780, 240, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbp1.setFont(font)
        self.rbp1.setAutoRepeat(True)
        self.rbp1.setObjectName("rbp1")
        self.rbp5 = QtGui.QPushButton(getrangedlg)
        self.rbp5.setGeometry(QtCore.QRect(810, 240, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbp5.setFont(font)
        self.rbp5.setAutoRepeat(True)
        self.rbp5.setObjectName("rbp5")
        self.srlp1 = QtGui.QPushButton(getrangedlg)
        self.srlp1.setGeometry(QtCore.QRect(400, 440, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlp1.setFont(font)
        self.srlp1.setAutoRepeat(True)
        self.srlp1.setObjectName("srlp1")
        self.srlp5 = QtGui.QPushButton(getrangedlg)
        self.srlp5.setGeometry(QtCore.QRect(430, 440, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlp5.setFont(font)
        self.srlp5.setAutoRepeat(True)
        self.srlp5.setObjectName("srlp5")
        self.srup1 = QtGui.QPushButton(getrangedlg)
        self.srup1.setGeometry(QtCore.QRect(660, 440, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srup1.setFont(font)
        self.srup1.setAutoRepeat(True)
        self.srup1.setObjectName("srup1")
        self.srup5 = QtGui.QPushButton(getrangedlg)
        self.srup5.setGeometry(QtCore.QRect(690, 440, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srup5.setFont(font)
        self.srup5.setAutoRepeat(True)
        self.srup5.setObjectName("srup5")
        self.srbp1 = QtGui.QPushButton(getrangedlg)
        self.srbp1.setGeometry(QtCore.QRect(770, 440, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbp1.setFont(font)
        self.srbp1.setAutoRepeat(True)
        self.srbp1.setObjectName("srbp1")
        self.srbp5 = QtGui.QPushButton(getrangedlg)
        self.srbp5.setGeometry(QtCore.QRect(800, 440, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbp5.setFont(font)
        self.srbp5.setAutoRepeat(True)
        self.srbp5.setObjectName("srbp5")
        self.rlm1 = QtGui.QPushButton(getrangedlg)
        self.rlm1.setGeometry(QtCore.QRect(410, 300, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlm1.setFont(font)
        self.rlm1.setAutoRepeat(True)
        self.rlm1.setObjectName("rlm1")
        self.rlm5 = QtGui.QPushButton(getrangedlg)
        self.rlm5.setGeometry(QtCore.QRect(440, 300, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlm5.setFont(font)
        self.rlm5.setAutoRepeat(True)
        self.rlm5.setObjectName("rlm5")
        self.rum1 = QtGui.QPushButton(getrangedlg)
        self.rum1.setGeometry(QtCore.QRect(670, 300, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rum1.setFont(font)
        self.rum1.setAutoRepeat(True)
        self.rum1.setObjectName("rum1")
        self.rum5 = QtGui.QPushButton(getrangedlg)
        self.rum5.setGeometry(QtCore.QRect(700, 300, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rum5.setFont(font)
        self.rum5.setAutoRepeat(True)
        self.rum5.setObjectName("rum5")
        self.rbm5 = QtGui.QPushButton(getrangedlg)
        self.rbm5.setGeometry(QtCore.QRect(810, 300, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbm5.setFont(font)
        self.rbm5.setAutoRepeat(True)
        self.rbm5.setObjectName("rbm5")
        self.rbm1 = QtGui.QPushButton(getrangedlg)
        self.rbm1.setGeometry(QtCore.QRect(780, 300, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbm1.setFont(font)
        self.rbm1.setAutoRepeat(True)
        self.rbm1.setObjectName("rbm1")
        self.srlm1 = QtGui.QPushButton(getrangedlg)
        self.srlm1.setGeometry(QtCore.QRect(400, 500, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlm1.setFont(font)
        self.srlm1.setAutoRepeat(True)
        self.srlm1.setObjectName("srlm1")
        self.srlm5 = QtGui.QPushButton(getrangedlg)
        self.srlm5.setGeometry(QtCore.QRect(430, 500, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlm5.setFont(font)
        self.srlm5.setAutoRepeat(True)
        self.srlm5.setObjectName("srlm5")
        self.srum1 = QtGui.QPushButton(getrangedlg)
        self.srum1.setGeometry(QtCore.QRect(660, 499, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srum1.setFont(font)
        self.srum1.setAutoRepeat(True)
        self.srum1.setObjectName("srum1")
        self.srum5 = QtGui.QPushButton(getrangedlg)
        self.srum5.setGeometry(QtCore.QRect(690, 500, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srum5.setFont(font)
        self.srum5.setAutoRepeat(True)
        self.srum5.setObjectName("srum5")
        self.srbm5 = QtGui.QPushButton(getrangedlg)
        self.srbm5.setGeometry(QtCore.QRect(800, 500, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbm5.setFont(font)
        self.srbm5.setAutoRepeat(True)
        self.srbm5.setObjectName("srbm5")
        self.srbm1 = QtGui.QPushButton(getrangedlg)
        self.srbm1.setGeometry(QtCore.QRect(770, 500, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbm1.setFont(font)
        self.srbm1.setAutoRepeat(True)
        self.srbm1.setObjectName("srbm1")

        self.retranslateUi(getrangedlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), getrangedlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), getrangedlg.reject)
        QtCore.QMetaObject.connectSlotsByName(getrangedlg)
        getrangedlg.setTabOrder(self.datafiles, self.selectx)
        getrangedlg.setTabOrder(self.selectx, self.xrangemin)
        getrangedlg.setTabOrder(self.xrangemin, self.rlp1)
        getrangedlg.setTabOrder(self.rlp1, self.rlp5)
        getrangedlg.setTabOrder(self.rlp5, self.rlpp1)
        getrangedlg.setTabOrder(self.rlpp1, self.rlpp5)
        getrangedlg.setTabOrder(self.rlpp5, self.rlmp1)
        getrangedlg.setTabOrder(self.rlmp1, self.rlmp5)
        getrangedlg.setTabOrder(self.rlmp5, self.rlm1)
        getrangedlg.setTabOrder(self.rlm1, self.rlm5)
        getrangedlg.setTabOrder(self.rlm5, self.xrangemax)
        getrangedlg.setTabOrder(self.xrangemax, self.rup1)
        getrangedlg.setTabOrder(self.rup1, self.rup5)
        getrangedlg.setTabOrder(self.rup5, self.rupp1)
        getrangedlg.setTabOrder(self.rupp1, self.rupp5)
        getrangedlg.setTabOrder(self.rupp5, self.rump1)
        getrangedlg.setTabOrder(self.rump1, self.rump5)
        getrangedlg.setTabOrder(self.rump5, self.rum1)
        getrangedlg.setTabOrder(self.rum1, self.rum5)
        getrangedlg.setTabOrder(self.rum5, self.rbp1)
        getrangedlg.setTabOrder(self.rbp1, self.rbp5)
        getrangedlg.setTabOrder(self.rbp5, self.rbpp1)
        getrangedlg.setTabOrder(self.rbpp1, self.rbpp5)
        getrangedlg.setTabOrder(self.rbpp5, self.rbmp1)
        getrangedlg.setTabOrder(self.rbmp1, self.rbmp5)
        getrangedlg.setTabOrder(self.rbmp5, self.rbm1)
        getrangedlg.setTabOrder(self.rbm1, self.rbm5)
        getrangedlg.setTabOrder(self.rbm5, self.selcolour)
        getrangedlg.setTabOrder(self.selcolour, self.colourdisp)
        getrangedlg.setTabOrder(self.colourdisp, self.srmin)
        getrangedlg.setTabOrder(self.srmin, self.srlp1)
        getrangedlg.setTabOrder(self.srlp1, self.srlp5)
        getrangedlg.setTabOrder(self.srlp5, self.srlpp1)
        getrangedlg.setTabOrder(self.srlpp1, self.srlmp5)
        getrangedlg.setTabOrder(self.srlmp5, self.srlmp1)
        getrangedlg.setTabOrder(self.srlmp1, self.srlpp5)
        getrangedlg.setTabOrder(self.srlpp5, self.srlm1)
        getrangedlg.setTabOrder(self.srlm1, self.srlm5)
        getrangedlg.setTabOrder(self.srlm5, self.srmax)
        getrangedlg.setTabOrder(self.srmax, self.srup1)
        getrangedlg.setTabOrder(self.srup1, self.srup5)
        getrangedlg.setTabOrder(self.srup5, self.srupp1)
        getrangedlg.setTabOrder(self.srupp1, self.srupp5)
        getrangedlg.setTabOrder(self.srupp5, self.srump1)
        getrangedlg.setTabOrder(self.srump1, self.srum1)
        getrangedlg.setTabOrder(self.srum1, self.srum5)
        getrangedlg.setTabOrder(self.srum5, self.srump5)
        getrangedlg.setTabOrder(self.srump5, self.srbp1)
        getrangedlg.setTabOrder(self.srbp1, self.srbp5)
        getrangedlg.setTabOrder(self.srbp5, self.srbpp1)
        getrangedlg.setTabOrder(self.srbpp1, self.srbpp5)
        getrangedlg.setTabOrder(self.srbpp5, self.srbmp1)
        getrangedlg.setTabOrder(self.srbmp1, self.srbmp5)
        getrangedlg.setTabOrder(self.srbmp5, self.srbm1)
        getrangedlg.setTabOrder(self.srbm1, self.srbm5)
        getrangedlg.setTabOrder(self.srbm5, self.buttonBox)

    def retranslateUi(self, getrangedlg):
        getrangedlg.setWindowTitle(QtGui.QApplication.translate("getrangedlg", "Configure ranges", None, QtGui.QApplication.UnicodeUTF8))
        getrangedlg.setToolTip(QtGui.QApplication.translate("getrangedlg", "Select the colour of the display line", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("getrangedlg", "Loading file(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.xrangemin.setToolTip(QtGui.QApplication.translate("getrangedlg", "Select minimum of range to display", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("getrangedlg", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.xrangemax.setToolTip(QtGui.QApplication.translate("getrangedlg", "Select maximum of range to display", None, QtGui.QApplication.UnicodeUTF8))
        self.rlmp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract .1 from range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlmp1.setText(QtGui.QApplication.translate("getrangedlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rlmp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract .5 from range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlmp5.setText(QtGui.QApplication.translate("getrangedlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rlpp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add .1 to range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlpp1.setText(QtGui.QApplication.translate("getrangedlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rlpp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add .5 to range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlpp5.setText(QtGui.QApplication.translate("getrangedlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rump1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract .1 from range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rump1.setText(QtGui.QApplication.translate("getrangedlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rupp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add .1 to range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rupp1.setText(QtGui.QApplication.translate("getrangedlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rump5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract .5 from range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rump5.setText(QtGui.QApplication.translate("getrangedlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rupp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add .5 to range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rupp5.setText(QtGui.QApplication.translate("getrangedlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 0.5 from range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp5.setText(QtGui.QApplication.translate("getrangedlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 0.1 to range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp1.setText(QtGui.QApplication.translate("getrangedlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 0.5 to range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp5.setText(QtGui.QApplication.translate("getrangedlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 0.1 to range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp1.setText(QtGui.QApplication.translate("getrangedlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("getrangedlg", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 0.5 to range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp5.setText(QtGui.QApplication.translate("getrangedlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 0.1 from range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp1.setText(QtGui.QApplication.translate("getrangedlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srump5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 0.5 from range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srump5.setText(QtGui.QApplication.translate("getrangedlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srump1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 0.1 from range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srump1.setText(QtGui.QApplication.translate("getrangedlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srmin.setToolTip(QtGui.QApplication.translate("getrangedlg", "This is the lower bound of the range", None, QtGui.QApplication.UnicodeUTF8))
        self.srmax.setToolTip(QtGui.QApplication.translate("getrangedlg", "This is the upper bound of the range.", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Contract ends of range by .1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp1.setText(QtGui.QApplication.translate("getrangedlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rbmp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Contract ends of range by .5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.rbmp5.setText(QtGui.QApplication.translate("getrangedlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rbpp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Expand ends of range by .1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.rbpp1.setText(QtGui.QApplication.translate("getrangedlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Expand ends of range by .1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp1.setText(QtGui.QApplication.translate("getrangedlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rbpp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Expand ends of range by .5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.rbpp5.setText(QtGui.QApplication.translate("getrangedlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Expand ends of range by .5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp5.setText(QtGui.QApplication.translate("getrangedlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rbmp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Contract ends of range by .1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.rbmp1.setText(QtGui.QApplication.translate("getrangedlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Contract ends of range by .5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp5.setText(QtGui.QApplication.translate("getrangedlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("getrangedlg", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.datafiles.setToolTip(QtGui.QApplication.translate("getrangedlg", "These are the spectra to be selected to compare ranges against", None, QtGui.QApplication.UnicodeUTF8))
        self.selcolour.setToolTip(QtGui.QApplication.translate("getrangedlg", "Select colour on display", None, QtGui.QApplication.UnicodeUTF8))
        self.selcolour.setText(QtGui.QApplication.translate("getrangedlg", "Choose Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.selectx.setToolTip(QtGui.QApplication.translate("getrangedlg", "Whether we apply the X range to plots", None, QtGui.QApplication.UnicodeUTF8))
        self.selectx.setText(QtGui.QApplication.translate("getrangedlg", "Select X Range", None, QtGui.QApplication.UnicodeUTF8))
        self.rlp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 1 to range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlp1.setText(QtGui.QApplication.translate("getrangedlg", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.rlp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 5 to range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlp5.setText(QtGui.QApplication.translate("getrangedlg", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.rup1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 1 to range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rup1.setText(QtGui.QApplication.translate("getrangedlg", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.rup5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 5 to range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rup5.setText(QtGui.QApplication.translate("getrangedlg", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.rbp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Expand ends of range by 1", None, QtGui.QApplication.UnicodeUTF8))
        self.rbp1.setText(QtGui.QApplication.translate("getrangedlg", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.rbp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Expand ends of range by 5", None, QtGui.QApplication.UnicodeUTF8))
        self.rbp5.setText(QtGui.QApplication.translate("getrangedlg", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.srlp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 1 to range min", None, QtGui.QApplication.UnicodeUTF8))
        self.srlp1.setText(QtGui.QApplication.translate("getrangedlg", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.srlp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 5 to range min", None, QtGui.QApplication.UnicodeUTF8))
        self.srlp5.setText(QtGui.QApplication.translate("getrangedlg", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.srup1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 1 to range max", None, QtGui.QApplication.UnicodeUTF8))
        self.srup1.setText(QtGui.QApplication.translate("getrangedlg", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.srup5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Add 5 to range min", None, QtGui.QApplication.UnicodeUTF8))
        self.srup5.setText(QtGui.QApplication.translate("getrangedlg", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.srbp1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Expand ends of range by 1", None, QtGui.QApplication.UnicodeUTF8))
        self.srbp1.setText(QtGui.QApplication.translate("getrangedlg", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.srbp5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Expand ends of range by 5", None, QtGui.QApplication.UnicodeUTF8))
        self.srbp5.setText(QtGui.QApplication.translate("getrangedlg", "+5", None, QtGui.QApplication.UnicodeUTF8))
        self.rlm1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 1 from range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlm1.setText(QtGui.QApplication.translate("getrangedlg", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.rlm5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 5 from range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlm5.setText(QtGui.QApplication.translate("getrangedlg", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.rum1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 1 from range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rum1.setText(QtGui.QApplication.translate("getrangedlg", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.rum5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 5 from range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rum5.setText(QtGui.QApplication.translate("getrangedlg", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.rbm5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Contract ends of range by 5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.rbm5.setText(QtGui.QApplication.translate("getrangedlg", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.rbm1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Contract ends of range by 1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.rbm1.setText(QtGui.QApplication.translate("getrangedlg", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.srlm1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 1 from range min", None, QtGui.QApplication.UnicodeUTF8))
        self.srlm1.setText(QtGui.QApplication.translate("getrangedlg", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.srlm5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 5 from range min", None, QtGui.QApplication.UnicodeUTF8))
        self.srlm5.setText(QtGui.QApplication.translate("getrangedlg", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.srum1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 1 from range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srum1.setText(QtGui.QApplication.translate("getrangedlg", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.srum5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Subtract 5 from range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srum5.setText(QtGui.QApplication.translate("getrangedlg", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.srbm5.setToolTip(QtGui.QApplication.translate("getrangedlg", "Contract ends of range by 5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbm5.setText(QtGui.QApplication.translate("getrangedlg", "-5", None, QtGui.QApplication.UnicodeUTF8))
        self.srbm1.setToolTip(QtGui.QApplication.translate("getrangedlg", "Contract ends of range by 1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbm1.setText(QtGui.QApplication.translate("getrangedlg", "-1", None, QtGui.QApplication.UnicodeUTF8))

